#!/bin/zsh
set -x
CONDITIONS_ROOT=/usr/local/munki/conditions
MUNKICON_ROOT=${CONDITIONS_ROOT}/munkicon

# -- Old 'com.github.carlashley.munkicon'
setopt +o nomatch  # Silence the 'zsh: no matches found'
/bin/rm -f ${CONDITIONS_ROOT}/com.github.carlashley.*.py 2>/dev/null
/bin/rm -rf ${MUNKICON_ROOT} 2>/dev/null
